spring:
  application:
    name: rss-tracker-bot
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:rss_tracker_db}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin}
      
bot:
  token: ${TELEGRAM_BOT_TOKEN}
  feeds: 
    page-size: ${FEEDS_PAGE_SIZE:10}